### ISSUE TITLE
Backtest strategies

### ISSUE THREAD

**Issue by StayFoolisj** [StayFoolisj/Cinnamon#7]
Need to be able to run backtesting on any strategy and visualise the results

**Task is complete when:**
- [ ] We can read historical OHLC data for any pair ([Issue 2]( https://github.com/Muggsie/Cinnamon/issues/2)) 
- [ ] We can backtest any strategy
- [ ] Results are visualised using ie. Matplotlib
