### ISSUE TITLE
Setup VPS in Europe

### ISSUE THREAD

**Issue by StayFoolisj** [StayFoolisj/Cinnamon#9]
Can't use US due to heavy restrictions for US citizens. Need to run Candy in close proximity to the exchange (same country, same city, same datacenter, same server rack, same server)

**Task is complete when:**
- [ ] Figured out locations of exchange servers 
- [ ] Setup of secure VPS is complete
- [ ] Successfully running Cinnamon on VPS
